Added option to create media collection for every form and page
alexander-schranz/sulu-form-bundle pull request #118
Opened 2016-11-10 17:51 UTC by alexander-schranz

The feature can be enabled with the following configuration: 

```
l91_sulu_form:
    collection:
        type: "multiple"
```

2016-11-10 18:12 UTC, wachterjohannes reviewed
Looks good maybe we review it together tomorrow

2016-11-10 18:12 UTC, wachterjohannes commented on DependencyInjection/Configuration.php
> +                    ->scalarNode('type')->defaultValue(L91SuluFormExtension::SINGLE_COLLECTION_TYPE)->end()
You could use enumNode

2016-11-10 18:27 UTC, alexander-schranz commented on DependencyInjection/Configuration.php
> +                    ->scalarNode('type')->defaultValue(L91SuluFormExtension::SINGLE_COLLECTION_TYPE)->end()
Maybe it should be called strategy instead oft type. Shouldnt be to fixed as enum. because it should be possible to create its own strategy.

2016-11-11 08:13 UTC, wachterjohannes commented on DependencyInjection/Configuration.php
> +                    ->scalarNode('type')->defaultValue(L91SuluFormExtension::SINGLE_COLLECTION_TYPE)->end()
then it should be validated in a compiler pass.

2016-11-11 08:13 UTC, wachterjohannes commented on DependencyInjection/Configuration.php
> +                    ->scalarNode('type')->defaultValue(L91SuluFormExtension::SINGLE_COLLECTION_TYPE)->end()
and the logic extracted into an own service!

2016-11-11 08:27 UTC, alexander-schranz commented
@wachterjohannes did rename the parameter to `media_collection_strategy` and call the new strategy `tree`.

2016-11-11 11:01 UTC, wachterjohannes commented
why not moving the strategy-logic into a service? one for tree and one for single collection?

2016-11-18 13:20 UTC, alexander-schranz commented
@wachterjohannes own services created for the collection strategy.

2016-11-21 07:56 UTC, wachterjohannes commented on Media/CollectionStrategyInterface.php
> +    public function getCollectionId(
quite a bit function parameter list. could this be a bit "thighter"?

2016-11-21 07:56 UTC, wachterjohannes commented
else ACK

2016-11-21 08:29 UTC, alexander-schranz commented on Media/CollectionStrategyInterface.php
> +    public function getCollectionId(
this is all what is needed for the tree strategy. we could just hide them in an `$options` array.

2016-11-22 06:28 UTC, wachterjohannes requested changes

2016-11-22 06:28 UTC, wachterjohannes commented on Media/CollectionStrategyTree.php
> +                $parentCollection = $this->collectionManager->getByKey($collectionKey, $locale);
avoid nesting try-catch blocks

2016-11-22 06:28 UTC, wachterjohannes commented on Media/CollectionStrategyInterface.php
> +    public function getCollectionId(
the first two could be combined with passing the for object (maybe?) for type, typeId, title maybe create a `FormEntity`? with that three properties?

2016-11-25 12:21 UTC, alexander-schranz commented on Media/CollectionStrategyInterface.php
> +    public function getCollectionId(
currently I would let it be as it is because in the future the media collection and co is not needed to create the Dynamic.php

2016-11-30 06:49 UTC, wachterjohannes commented
ACK

2016-11-30 07:00 UTC, merged