WIP: Add Dates to CSV Export Overlay
alexander-schranz/sulu-form-bundle pull request #137
Opened 2017-02-01 16:45 UTC by thomasduenser

TODO:
- [ ] Translations

2017-02-02 09:05 UTC, alexander-schranz requested changes

2017-02-02 09:05 UTC, alexander-schranz commented on Controller/DynamicController.php
> +    protected function findEntries(
move querylogic into DynamicRepository

2017-02-02 09:05 UTC, alexander-schranz commented on Resources/public/js/components/csv-export/form.html
> +<div class="grid">
use twig template here and extend from default when possible.
else I would prefer just append your additional fields to the sulu template.

2017-02-02 09:05 UTC, alexander-schranz commented on Resources/public/js/components/csv-export/main.js
> +define(['text!./form.html'], function(form) {
use twig template when it is changed in sulu/sulu.

2017-02-02 09:05 UTC, alexander-schranz commented on Controller/DynamicController.php
> +        $criteria = new Criteria();
use the normal queryBuilder instead of criteria

2017-02-02 09:05 UTC, alexander-schranz commented on Controller/DynamicController.php
> +        $fromDate = $request->get('fromDate');
are not needed as they should be inside the `$filters`  variable.

2017-02-02 09:05 UTC, alexander-schranz commented on Controller/DynamicController.php
> +            'form' => $this->loadForm($request),
looks like a bc break why did this changed?

2017-02-02 09:05 UTC, alexander-schranz commented on Controller/DynamicController.php
> +        $entries = $this->findEntries(
```
$repository->findEntries($filters, $limit, $offset, $sortBy, $sortOrder);
```

2017-02-02 09:06 UTC, alexander-schranz commented on Resources/public/js/components/csv-export/main.js
> + * (c) MASSIVE ART WebServices GmbH
remove

2017-02-02 09:19 UTC, alexander-schranz commented on Resources/public/js/components/content/list/main.js
>                                                  App.start([{
```
App.start([{
       name: 'csv-export@l91suluform',
       options: {
            el: $container
       }
    }]).fail(function() {

       console.info('For date range specific export you need sulu atleast 1.5')   ;

       App.start([{
           name: 'csv-export@suluadmin',
          options: {
                el: $container
           }
    }]);
});
```

2017-02-02 14:55 UTC, thomasduenser commented on Resources/public/js/components/csv-export/form.html
> +<div class="grid">
Done!

2017-02-02 16:42 UTC, alexander-schranz commented on Repository/DynamicRepository.php
> +            $queryBuilder->setParameters([
this does reset all previous added parameters use `setParameter` foreach

2017-02-02 16:43 UTC, alexander-schranz commented on Repository/DynamicRepository.php
> +    protected function addDateRangeFilter(&$queryBuilder, $fromDate, $toDate)
$queryBuilder is an object and dont need `&`!

2017-02-02 16:44 UTC, alexander-schranz commented on Repository/DynamicRepository.php
> +     * @param QueryBuilder $queryBuilder
add comment

2017-02-02 16:50 UTC, alexander-schranz requested changes

2017-02-02 16:50 UTC, alexander-schranz commented on Repository/DynamicRepository.php
> +     * @param array $filters
add comment

2017-02-02 16:50 UTC, alexander-schranz commented on Repository/DynamicRepository.php
> +        } catch (NoResultException $exception) {
this try and catch is not needed as it is not a `getSingleResult` so it will not throw a NoResultException

2017-02-02 16:50 UTC, alexander-schranz commented on Controller/DynamicController.php
> +            $total = count($repository->getByFilters($filters));
as this is not proxied like findBy we will create an own `count` function

2017-02-02 16:50 UTC, alexander-schranz commented on Repository/DynamicRepository.php
> +        $this->addDateRangeFilter($queryBuilder, $fromDate, $toDate);
move addFilter to an own function to use it for the `count` function.

2017-02-02 16:50 UTC, alexander-schranz commented on Controller/DynamicController.php
> +        $entries = $repository->getByFilters(
could we call it `findByFilters` or does this conflict?

2017-02-03 10:55 UTC, alexander-schranz approved these changes

2017-02-03 14:42 UTC, merged